# Generated by Django 4.0.5 on 2022-06-25 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokemon', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pokemons', to=settings.AUTH_USER_MODEL),
        ),
    ]
